// Code generated by MockGen. DO NOT EDIT.
// Source: products_repository.go
//
// Generated by this command:
//
//	mockgen -source=products_repository.go -destination=mock_products_repository.go -package=models
//

// Package models is a generated GoMock package.
package models

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockProductFetcher is a mock of ProductFetcher interface.
type MockProductFetcher struct {
	ctrl     *gomock.Controller
	recorder *MockProductFetcherMockRecorder
	isgomock struct{}
}

// MockProductFetcherMockRecorder is the mock recorder for MockProductFetcher.
type MockProductFetcherMockRecorder struct {
	mock *MockProductFetcher
}

// NewMockProductFetcher creates a new mock instance.
func NewMockProductFetcher(ctrl *gomock.Controller) *MockProductFetcher {
	mock := &MockProductFetcher{ctrl: ctrl}
	mock.recorder = &MockProductFetcherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProductFetcher) EXPECT() *MockProductFetcherMockRecorder {
	return m.recorder
}

// GetAllProducts mocks base method.
func (m *MockProductFetcher) GetAllProducts() ([]Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllProducts")
	ret0, _ := ret[0].([]Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllProducts indicates an expected call of GetAllProducts.
func (mr *MockProductFetcherMockRecorder) GetAllProducts() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllProducts", reflect.TypeOf((*MockProductFetcher)(nil).GetAllProducts))
}
